logging:
  level:
    org.springframework: INFO
    br.com.devmedia.jm.woki.airport: INFO
server:
  port: 8080
  contextPath: /openflights
spring:
  messages:
    basename: messages
    encoding: ISO-8859-1  #UTF-8
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    platform: h2
    data:   { "data*.sql","data-h123.sql" }
    schema: { "schema*.sql",  "/database/schema-h2.sql" }
    